### ISSUE TITLE
A section in readme about relation to other GDG projects

### ISSUE THREAD

**Issue by friedger** [gdg-x/nexus#3]
It looks like an addition to firefly with focus on chapters (instead of events).

It might be a replacement of boomerang in the future.

**Comment by Splaktar** [comment]
It is in addition to Firefly. It depends on the Hub and Meetup API.

It's not really a replacement for Boomerang unless chapters don't want a website and just want to use the chapter page on Nexus.

I'll try to add more details in the future.

**Comment by Splaktar** [comment]
No longer needed as this project is being deprecated.
